import React, { createContext, useEffect, useState } from "react";
import LocalizedStrings from "react-localization";
import { API_DEFAULT_LANGUAGE } from "./constants/apiConstants";

const strings = new LocalizedStrings({
  en: {
    login: "Login",
    logout: "Logout",
    myProfile: "My Profile",
    stlViewer: "3D Viewer",
    manageUsers: "Manage Users",
    manageDomains: "Manage Domains",
    manageRoles: "Manage Roles",
    settings: "Settings",
    welcome: "Welcome",
    videoPhoto: "Video/Photo",
    chat: "Chat",
    revenueReport: "Revenues",
    timesheet: "Timesheet",
    //timesheetin käännökset
    timesheetNameLabel: "Timesheet name",
    timesheetNamePlaceholder: "Enter timesheet name",
    employeeLabel: "Employee",
    employeePlaceholder: "Enter your name",
    jobTitleLabel: "Job title",
    jobTitlePlaceholder: "Enter job title",
    projectLabel: "Cost center / Project",
    projectPlaceholder: "Enter cost center or project",
    dateLabel: "Date",
    startTimeLabel: "Start time",
    endTimeLabel: "End time",
    normalHoursLabel: "Normal hours",
    normalHoursPlaceholder: "Enter hours worked",
    extrasLaLabel: "Extras Sat",
    extrasSuLabel: "Extras Sun",
    extrasEveningLabel: "Extras Evening",
    extrasNightLabel: "Extras Night",
    extrasPlaceholder: "Enter hours if any", 
    showExtrasPlaceholder: "Fill in",
    overtimeVrk50Label: "Overtime day 50%",
    overtimeVrk100Label: "Overtime day 100%",
    overtimeVko50Label: "Overtime week 50%",
    overtimeVko100Label: "Overtime week 100%",
    overtimePlaceholder: "Enter hours if any", 
    showOvertimePlaceholder: "Fill in",   
    atvLabel: "ATV (holiday hours)",
    travelLabel: "Travel hours",
    mealLabel: "Meal compensation",
    kmLabel: "Mileage",
    kmPlaceholder: "Enter kilometers",
    toolCompLabel: "Tool compensation",
    toolCompPlaceholder: "Enter euros",
    kmNoteLabel: "Mileage note",
    kmNotePlaceholder: "Purpose of travel (e.g., meeting)",
    kmDescInfo: "Fill in",
    noteLabel: "Notes",
    notePlaceholder: "Short note, e.g., delay or special situation",
    memoLabel: "MEMO",
    memoPlaceholder: "Write detailed description or memo here",
    toggleExtrasShow: "Show extras",
    toggleExtrasHide: "Hide extras",
    toggleOvertimeShow: "Show overtime",
    toggleOvertimeHide: "Hide overtime",
    addRowButton: "➕ Add row",
    clearAllButton: "🗑 Clear all",
    summaryHeader: "Summary",
  },
  fi: {
    login: "Kirjaudu sisään",
    logout: "Kirjaudu ulos",
    myProfile: "Oma Profiili",
    stlViewer: "3D-katseluohjelma",
    manageUsers: "Käyttäjät",
    manageDomains: "Domainit",
    manageRoles: "Roolit",
    settings: "Asetukset",
    welcome: "Tervetuloa",
    videoPhoto: "Video/Kuva",
    chat: "Chatti",
    revenueReport: "Liikevaihtod",
    timesheet: "Tuntikortti",
    //timesheetin käännökset
    timesheetNameLabel: "Tuntikortin nimi",
    timesheetNamePlaceholder: "Syötä tuntikortin nimi",
    employeeLabel: "Työntekijä",
    employeePlaceholder: "Syötä nimesi",
    jobTitleLabel: "Ammattinimike",
    jobTitlePlaceholder: "Syötä ammatti",
    projectLabel: "Kustannuspaikka ja/tai projekti",
    projectPlaceholder: "Syötä kustannuspaikka tai projekti",
    dateLabel: "PVM ",
    startTimeLabel: "Työajan alku",
    endTimeLabel: "Työajan loppu",
    normalHoursLabel: "Norm. tunnit",
    normalHoursPlaceholder: "Syötä tehdyt työtunnit",
    extrasLaLabel: "Lisät la",
    extrasSuLabel: "Lisät su",
    extrasEveningLabel: "Lisät Ilta",
    extrasNightLabel: "Lisät Yö",
    extrasPlaceholder: "Syötä tunteina, jos on",
    showExtrasPlaceholder: "Täytä",
    overtimeVrk50Label: "Ylityö vrk 50%",
    overtimeVrk100Label: "Ylityö vrk 100%",
    overtimeVko50Label: "Ylityö vko 50%",
    overtimeVko100Label: "Ylityö vko 100%",
    overtimePlaceholder: "Syötä tunteina, jos on",
    showOvertimePlaceholder: "Täytä",   
    atvLabel: "ATV (arkipyhättunnit)",
    travelLabel: "Matkatunnit",
    mealLabel: "Ateriakorvaus",
    kmLabel: "Kilometrikorvaus",
    toolCompLabel: "Työkalukorvaus",
    toolCompLabelPlaceholder: "Syötä euroina",
    kmNoteLabel: "Kilometrikorvaus selite",
    kmNotePlaceholder: "Matkan tarkoitus (esim. työpalaveri)",
    kmDescInfo: "Täytä",
    noteLabel: "Huomioita",
    notePlaceholder: "Lyhyt huomio, esim. myöhästyminen tai erityisolosuhde",
    memoLabel: "MEMO",
    memoPlaceholder: "Kirjoita tarkempi selite tai muistiinpano tähän",
    toggleExtrasShow: "Lisät näkyviin",
    toggleExtrasHide: "Lisät piiloon",
    toggleOvertimeShow: "Ylityöt näkyviin",
    toggleOvertimeHide: "Ylityöt piiloon",
    addRowButton: "➕ Lisää rivi",
    clearAllButton: "🗑 Tyhjennä kaikki",
    summaryHeader: "Yhteenveto",
  },
  sv: {
    login: "Logga in",
    logout: "Logga ut",
    myProfile: "Min Profil",
    stlViewer: "3D-visningsprogram",
    manageUsers: "Hantera användare",
    manageDomains: "Hantera domäner",
    manageRoles: "Hantera roller",
    settings: "Inställningar",
    welcome: "Välkommen",
    videoPhoto: "Video/Foto",
    chat: "Chatt",
    revenueReport: "Intäkter",
    timesheet: "Tidrapport",
    //timesheetin käännökset
    timesheetNameLabel: "Tidkortets namn",
    timesheetNamePlaceholder: "Ange tidkortets namn",
    employeeLabel: "Anställd",
    employeePlaceholder: "Ange ditt namn",
    jobTitleLabel: "Jobbtitel",
    jobTitlePlaceholder: "Ange jobbtitel",
    projectLabel: "Kostnadsställe / Projekt",
    projectPlaceholder: "Ange kostnadsställe eller projekt",
    dateLabel: "Datum",
    startTimeLabel: "Starttid",
    endTimeLabel: "Sluttid",
    normalHoursLabel: "Normaltimmar",
    normalHoursPlaceholder: "Ange arbetade timmar",
    extrasLaLabel: "Tillägg lör",
    extrasSuLabel: "Tillägg sön",
    extrasEveningLabel: "Tillägg kväll",
    extrasNightLabel: "Tillägg natt",
    extrasPlaceholder: "Ange timmar om det finns",
    showExtrasPlaceholder: "Fylla i",
    overtimeVrk50Label: "Övertid dag 50%",
    overtimeVrk100Label: "Övertid dag 100%",
    overtimeVko50Label: "Övertid vecka 50%",
    overtimeVko100Label: "Övertid vecka 100%",
    overtimePlaceholder: "Ange timmar om det finns",
    showOvertimePlaceholder: "Fylla i",   
    atvLabel: "ATV (helgtimmar)",
    travelLabel: "Resetimmar",
    mealLabel: "Måltidsersättning",
    kmLabel: "Kilometersättning",
    toolCompLabel: "Verktygsersättning",
    toolCompPlaceholder: "Ange i euro",
    kmNoteLabel: "Kilometersättning anteckning",
    kmNotePlaceholder: "Syfte med resan (t.ex. möte)",
    kmDescInfo: "Fylla i",
    noteLabel: "Noteringar",
    notePlaceholder: "Kort notering, t.ex. försening eller särskilda omständigheter",
    memoLabel: "MEMO",
    memoPlaceholder: "Skriv detaljerad beskrivning eller anteckning här",
    toggleExtrasShow: "Visa tillägg",
    toggleExtrasHide: "Dölj tillägg",
    toggleOvertimeShow: "Visa övertid",
    toggleOvertimeHide: "Dölj övertid",
    addRowButton: "➕ Lägg till rad",
    clearAllButton: "🗑 Rensa allt",
    summaryHeader: "Sammanfattning",
  },
});

const LanguageContext = createContext();

const LanguageProvider = ({ children }) => {
  const defaultLanguage =
    new URLSearchParams(window.location.search).get("lang") ||
    API_DEFAULT_LANGUAGE ||
    "en";
  const [language, setLanguage] = useState(defaultLanguage);

  useEffect(() => {
    strings.setLanguage(language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, strings }}>
      {children}
    </LanguageContext.Provider>
  );
};

export { LanguageContext, LanguageProvider };
